#!/bin/bash
#SBATCH --job-name=REFINE
###########RESOURCES###########
#SBATCH --partition=48-4
#SBATCH --gres=gpu:4
#SBATCH --mem=100G
#SBATCH --cpus-per-task=32
###############################
#SBATCH --output=TEST.out
#SBATCH --error=TEST.err
#SBATCH -v
#######For venv users (if you use Anaconda, please comment out the following) ######
#. /usr/share/Modules/init/profile.sh
#module load cuda/11.3
#module load python/3.9.5
#source ~/venv/pytorch/bin/activate
#######For Anacond users (if you use venv, please comment out the following) ######
source ~/anaconda3/etc/profile.d/conda.sh
conda activate llavaod

srun  python main.py
